name = "ggwifi-admin-portal"
compatibility_date = "2024-01-01"

[env.production]
pages_build_output_dir = "dist"

[env.production.vars]
VITE_API_URL = "https://api.ggwifi.co.tz/api/v1"
VITE_API_BASE_URL = "https://api.ggwifi.co.tz/api/v1"
VITE_APP_DOMAIN = "admin.ggwifi.co.tz"
VITE_APP_NAME = "GGWIFI Admin Portal"
VITE_ENVIRONMENT = "production"
